[package]
name = "topcodes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2" # TODO remove once tests are in place and debugging is complete.

[dev-dependencies]
image = "0.24.2"

[features]
visualize = []
